apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http
  annotations:
    kubernetes.io/ingress.class: contour-internal
    ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - host: argocd.k3s.nextcloud.bazin-jeremy.com
        http:
        paths:
        - path: /
            pathType: Prefix
            backend:
            service:
                name: argocd-server
                port:
                name: http
  ingressClassName: nginx