---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc-config
data:

  # file-like keys
  frpc.ini: "
[common]\n
server_addr = {{ .Values.subDomain }}.bazin-jeremy.com\n
server_port = 7000\n
tls_enable = true\n
dial_server_timeout = 60\n
\n
[dev-k3s-http]\n
type = http\n
local_ip = hello.hello.svc.cluster.local\n
local_port = 80\n
remote_port = 8081\n
subdomain = {{ .Values.localDomain }}\n
\n
[dev-k3s-https]\n
type = https\n
local_ip = nginx-service.ingress.svc.cluster.local\n
local_port = 443\n
remote_port = 8443\n
subdomain = {{ .Values.localDomain }}\n
"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fprc-deploy
spec:
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
      - name: fprc
        image: snowdreamtech/frpc:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: config
          mountPath: /etc/frp/
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: frpc-config



