---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frpc
  namespace: ingress
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  "frpc.ini": "
[common]
server_addr = {{ .Values.subDomain }}.bazin-jeremy.com
server_port = 7000
tls_enable = true
dial_server_timeout = 60

[nextcloud-dev-http]
type = http
local_ip = localhost
local_port = 80
remote_port = 80
subdomain = dev2

[nextcloud-dev-https]
type = https
local_ip = localhost
local_port = 8443
remote_port = 443
subdomain = dev2
"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fprc
  namespace: ingress
spec:
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      containers:
      - name: fprc
        image: snowdreamtech/frpc:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: config
          mountPath: /etc/frp/frpc.ini
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: frpc-config

