apiVersion: v1
kind: Service
metadata:
  name: mysql-1
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-1
spec:
  selector:
    matchLabels:
      app: mysql-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-1
    spec:
      containers:
      - image: mysql:latest
        name: mysql-1
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: config
          mountPath: /etc/mysql/conf.d/
          readOnly: true
        
        
      volumes:
      - name: config
        configMap:
          name: mysql-config

      #   volumeMounts:
      #   - name: mysql-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pv-claim