nextcloud:
  nextcloud: 
    host: nextcloud.k3s.bazin-jeremy.com
    updatae: 1
  persistence:
    enabled: true
    storageClass: local-data-path
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    className: nginx
    tls:
    - hosts:
      - nextcloud.k3s.bazin-jeremy.com
      secretName: nextcloud-tls