apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress-http
  namespace: argocd
spec:
  rules:
  - host: argocd.k3s.nextcloud.bazin-jeremy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
  ingressClassName: nginx