---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Skyt0a/k3s.git
    targetRevision: HEAD
    path: ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 2
      backoff:
        duration: 2s
        factor: 2
        maxDuration: 3m0s
