apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deploy
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    spec:
      containers:
      - name: helloworld
        metadata:
          app: helloworld
        image: karthequian/helloworld:latest
        ports:
        - containerPort: 80