grafana:
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
    - monitoring.k3s.bazin-jeremy.com
    tls:
    - hosts:
      - monitoring.k3s.bazin-jeremy.com
      secretName: grafana-tls


prometheus:
  extraScrapeConfigs: |
    - job_name: 'argocd'
      metrics_path: /metrics
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - argocd.base-monitoring.svc.cluster.local:8082