grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - monitoring.k3s.bazin-jeremy.com
    tls:
    - hosts:
      - monitoring.k3s.bazin-jeremy.com
      secretName: grafana-tls


prometheus:
  extraScrapeConfigs: |
    - job_name: 'argocd'
      metrics_path: /metrics
      static_configs:
        - targets:
          - argocd.base-monitoring.svc.cluster.local:8082