---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: network
  source:
    repoURL: "https://github.com/Skyt0a/k3s.git"
    targetRevision: HEAD
    path: ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: base-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
