---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-setup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Skyt0a/k3s.git"
    targetRevision: HEAD
    path: longhorn-setup
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
