apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: longhorn
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.4.x
    chart: longhorn
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.host
          value: longhorn.k3s.bazin-jeremy.com
        - name: ingress.ingressClassName
          value: nginx
        - name: defaultSettings.defaultReplicaCount
          value: '1'
        - name: longhornUI.replicas
          value: '1'
        - name: persistence.defaultClassReplicaCount
          value: '1'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
