apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-1
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-2
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"