mysql:
  instances:
  - name: 1
    initialMaster: true
  - name: 2
    initialMaster: false
  - name: 3
    initialMaster: false
  - name: 4
    initialMaster: false
  - name: 5
    initialMaster: false
  

nextcloud:
  nextcloud: 
    host: nextcloud.k3s.bazin-jeremy.com
    updatae: 1
  persistence:
    enabled: true
    storageClass: local-path
    nextcloudData:
      enabled: true
      storageClass: local-path
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    className: nginx
    tls:
    - hosts:
      - nextcloud.k3s.bazin-jeremy.com
      secretName: nextcloud-tls
  internalDatabase:
    enabled: false
  externalDatabase:
    enabled: true
    host: mysql-1.nextcloud.svc.cluster.local
    database: mysql-1.nextcloud.svc.cluster.local
    user: root
    password: password
    type: mysql