"argo-cd":
  # Enabled all metric scrap by prometheus
  controller:
    metrics:
      enabled: true

  # Ingress
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
      - argocd.k3s.bazin-jeremy.com
      tls:
      - hosts:
        - argocd.k3s.bazin-jeremy.com
        secretName: argocd-tls

  dex:
    enabled: true
    config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv1.3dea4dba1f7b8aee
          clientSecret: a6bb0d433aaeae6f17181d725c6a4ccb07bbf7bc 
          orgs:
          - name: "@Skyt0a"
  
  configs:
    cm:
      exec.enabled: true

  # ArgoCD Application status detection
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs