argocd:
  # Enabled all metric scrap by prometheus
  controller.metrics.enabled: true

  # Ingress
  server.ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - argocd.k3s.bazin-jeremy.com
    tls:
    - hosts:
      - argocd.k3s.bazin-jeremy.com
      secretName: argocd-tls

  dex.enabled: false

  # ArgoCD Application status detection
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs