"argo-cd":
  # Enabled all metric scrap by prometheus
  controller:
    metrics:
      enabled: true

  # Ingress
  server:
    extraArgs: 
      - "--dex-server-plaintext"
      - "--dex-server=http://argocd-dex-server.argocd.svc.cluster.local:5556"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
      - argocd.k3s.bazin-jeremy.com
      tls:
      - hosts:
        - argocd.k3s.bazin-jeremy.com
        secretName: argocd-tls

  dex:
    enabled: true
    extraArgs:
      - "--disable-tls"
  
  configs:
    cm:
      admin.enabled: false
      
      exec.enabled: true
      url: "https://argocd.k3s.bazin-jeremy.com"
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: Iv1.3dea4dba1f7b8aee
              clientSecret: 14b73cd0d3e1fdf046e4992adbf1f7bf43d7a7dc
            useLoginAsID: true

    rbac:
      policy.default: "role:admin"
      policy.csv: |
        g, bazin.jer@gmail.com, role:admin
  # ArgoCD Application status detection
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs