apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nextcloud
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'nextcloud'
    server: '*'