apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-data-path
provisioner: cluster.local/local-path-provisioner
parameters:
  nodePath: /data
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Immediate